# Generated by Django 4.1.3 on 2022-11-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_answer_question_alter_quizzes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
    ]
